import React from 'react'
import ContactUs from '../Components/ContactUs';
export const metadata = {
    title: "Contact Us | MayBell - Online Store",
    description: "Generated by create next app",
};

export default function page() {
  return (
    <>
<ContactUs/>
    </>
  )
}
