import React from 'react'
import AboutUs from '../Components/AboutUs';


export const metadata = {
    title: "Catalog | MayBell - Online Store",
    description: "Generated by create next app",
};

export default function page() {
    return (
        <>
          <AboutUs />
        </>
    )
}