import ProductDetails from '@/app/Components/ProductDetails'
import React from 'react'
import ViewCart from '../Components/ViewCart';
export const metadata = {
    title: "view-cart| MayBell - Online Store",
    description: "Generated by create next app",
};

export default function page() {
  return (
    <>
<ViewCart/>
    </>
  )
}
