'use client'


import { Provider } from "react-redux";
import Footer from "./Components/Footer";
import Header from "./Components/Header";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { store } from "./ReduxToolkit/store";

// export const metadata = {
//   title: "MayBell-Online Furniture store",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <Provider store={store}>
          <ToastContainer />
          <Header />
          {children}
          <Footer />
        </Provider>


      </body>

    </html>
  );
}