
import React from 'react'
import MyAccount from '../Components/MyAccount';
export const metadata = {
    title: "My Account| MayBell - Online Store",
    description: "Generated by create next app",
};

export default function page() {
  return (
    <>
<MyAccount/>
    </>
  )
}
